# Jekyll configuration

name: ok97465
description: 방관자

# Url is currently only used only for the RSS feed in feed.xml
url: https://ok97465.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: ok97465
copyright: 2018-

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: false
  pinterest: false
  email: true

social:
  github: ok97465
  stackoverflow: '9015220/lowqualitydelivery'
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-125307858-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ok97465s-blog
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  syntax_highlighter: rouge
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
